src/Entity/Films.php
<?php

namespace App\Entity;

use App\Repository\FilmsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmsRepository::class)
 */
class Films
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $resume;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_de_sortie;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $affiche;

    /**
     * @ORM\ManyToOne(targetEntity=Genres::class, inversedBy="films")
     */
    private $genre;

    /**
     * @ORM\ManyToMany(targetEntity=Acteurs::class, inversedBy="films")
     */
    private $acteurs;

    public function __construct()
    {
        $this->acteurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getAnneeDeSortie(): ?int
    {
        return $this->annee_de_sortie;
    }

    public function setAnneeDeSortie(int $annee_de_sortie): self
    {
        $this->annee_de_sortie = $annee_de_sortie;

        return $this;
    }

    public function getAffiche()
    {
        return $this->affiche;
    }

    public function setAffiche( $affiche): self
    {
        $this->affiche = $affiche;

        return $this;
    }

    public function getGenre(): ?Genres
    {
        return $this->genre;
    }

    public function setGenre(?Genres $genre): self
    {
        $this->genre = $genre;

        return $this;
    }
    
    /**
     * @return Collection<int, Acteurs>
     */
    public function getActeurs(): Collection
    {
        return $this->acteurs;
    }
    
    public function addActeur(Acteurs $acteur): self
    {
        if (!$this->acteurs->contains($acteur)) {
            $this->acteurs[] = $acteur;
        }
    
        return $this;
    }
    
    public function removeActeur(Acteurs $acteur): self
    {
        $this->acteurs->removeElement($acteur);

        return $this;
    }
}

src/Form/FilmsType.php
<?php

namespace App\Form;

use App\Entity\Acteurs;
use App\Entity\Films;
use App\Entity\Genres;
use DateTimeInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('resume',TextType::class)
            ->add('AnneeDeSortie',IntegerType::class)
            ->add('Affiche',FileType::class,[
               'data_class'=>null
            ])
            ->add('Genre', EntityType::class, [
               
                'class' => Genres::class,
                'choice_label' => 'nom',
                ])
                ->add('acteurs', EntityType::class,[
                    'class' => Acteurs::class,
                    'choice_label' => 'nom',
                    'expanded' => true,
                    'multiple' => true,
                    
                ])
                    
              
            ->add('Ajouter',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
           
            'data_class' => Films::class,
           
        ]);
    }
}

src/Controller/FilmsController.php
<?php



namespace App\Controller;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Films;
use App\Entity\Search;
use App\Form\FilmsType;
use App\Form\SearchType;
use App\Repository\FilmsRepository;
use App\Repository\GenresRepository;
use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;

class FilmsController extends AbstractController{

    /**
     *@Route("/Films" , name="films")
    */
    public function Afficher_films(FilmsRepository $res,Request $request):Response{
         $films=$res->findAll();
      


        return $this->render('/Films/Films.html.twig',[
            'films'=>$films,
          
        ]);
    }
   
        /**
     *@Route("/Film/{id}" , name="film")
    */
    public function Afficher_film(FilmsRepository $res, $id):Response{
        $film=$res->find($id);
   
     
       
        return $this->render('/Films/film.html.twig',[
           'film'=>$film
       ]);
   }
         /**
     *@Route("/Film/{id}/genre" , name="listg")
    */
    public function list_genre(FilmsRepository $res, $id):Response{
      $film=$res->find($id);
    $search=  $film->getGenre()->getId();
  
      $recherches=$res->findBySearch($search);

      
      return $this->render('/Films/search.html.twig',[
         'recherches'=>$recherches
     ]);
 }




    /**
     * @Route("/Films/Creation", name="filmadd")
     */
    public function creation(EntityManagerInterface $manager, Request $request):Response{
        $film=new Films();
        $form=$this->createForm(FilmsType::class,$film);
       
      $form->handleRequest($request);
      if($form->isSubmitted()&& $form->isValid()){
    

        $file=$film->getAffiche();
        $fileName=$file->getClientOriginalName();
        try {
          $file->move(
              $this->getParameter('photo_directory'),
              $fileName
          );
      } catch (FileException $e) {
       
      }
              
          $film->setAffiche($fileName);
   

        $manager->persist($film);
        $manager->flush();
    $this->addFlash('succes',"bien ajouter");
    return $this->redirectToRoute("films");
          }
     
          return $this->render("Films/Creation.html.twig",[
            'form'=>$form->createView()
        ]);
     }
       /**
     * @Route("/Films/{id}/Edit", name="filmed")
     */
    public function edit(Request $request, Films $film):Response{
      
        $form=$this->createForm(FilmsType::class,$film);
      
      $form->handleRequest($request);
      if($form->isSubmitted()&& $form->isValid()){
        $file=$film->getAffiche();
        $fileName=$file->getClientOriginalName();
  try {
    $file->move(
        $this->getParameter('photo_directory'),
        $fileName
    );
} catch (FileException $e) {
 
}
    $film->setAffiche($fileName);
        $entityManager=$this->getDoctrine()->getManager();
        $entityManager->persist($film);
        $entityManager->flush();
        $this->addFlash('succes'," film bien modifier");
        return $this->redirectToRoute('films');
      

     }
          return $this->render("Films/Creation.html.twig",[
            'form'=>$form->createView()
        ]);
     }


    /**
     * @Route("/Films/{id}/Supprimer", name="filmsup")
    */
    public function delete(EntityManagerInterface $manager,Films $id):Response{
        $manager->remove($id);
        $manager->flush();
        $this->addFlash('succes',"film bien supprimer");
      
 
         return $this->redirectToRoute('films');
     }
  
}

?>

templates/Films/Creation.html.twig
{% extends "base.html.twig" %}

{% block title %}Creer  un film{% endblock %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block body %}

<div class="container">
    <h1>Creer un film</h1>
    {{form_start(form)}}
    <div class="row">
        <div class="col-md-4">{{form_row(form.titre)}}</div>
        <div class="col-md-4">{{form_row(form.resume)}}</div>
    
    </div>
    <div class="row">
        <div class="col-md-2">{{form_row(form.AnneeDeSortie)}}</div>
       
        <div class="col-md-2">{{form_row(form.Affiche)}}</div>
        <div class="col-md-2">{{form_row(form.Genre)}}</div>
    </div>
    <div class="row">
    <div class="col-md-2">{{form_row(form.acteurs)}}</div>
    </div>
{{form_widget(form)}}
{{form_end(form)}}
 
</div>




{% endblock %}

templates/Films/Films.html.twig
{% extends "base.html.twig" %}

{% block title %}Panel Admin{% endblock %}



{% block body %}

<div class="continaire-mt-4">
    <h1>Gérer les films</h1>
    <a href="{{path("filmadd")}}" class="btn btn-secondary">Ajouter un film</a>
{%for message in app.flashes('succes')%}
 <div class="alert alert-success">
    {{message}}
 </div>
{%endfor%}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>titre</th>
                <th>Genre</th>
                <th>Actions</th>
              

            </tr>
        </thead>
        <tbody>
            {% for film in films %}
            <tr>
                <td>{{film.id}}</td>
             
                <td><a href="{{path('film',{id:film.id})}}">{{ film.titre}}</a></td>
                <td><a href="{{path("listg",{id:film.id})}}">{{film.genre.nom}}</td>
             
                <td><a href="{{path("filmed",{id:film.id})}}" class="btn btn-secondary">Modifier</a></td>
        
                <td><a href="{{path("filmsup",{id:film.id})}}" class="btn btn-secondary">Supprimer</a></td>
            </tr>
            
            
            {% endfor %}
        </tbody>
    </table>
</div>

 

{% endblock %}

templates/Films/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Modifier  un film{% endblock %}

{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block body %}

<div class="container">
    <h1>Modifier ce film</h1>
    {{form_start(form)}}
    <div class="row">
        <div class="col-md-4">{{form_row(form.titre)}}</div>
        <div class="col-md-4">{{form_row(form.resume)}}</div>
    
    </div>
    <div class="row">
        <div class="col-md-2">{{form_row(form.anneeDeSortie)}}</div>
        <div class="col-md-2">{{form_row(form.acteurs)}}</div>
        <div class="col-md-2">{{form_row(form.affiche)}}</div>
      
    </div>
    
{{form_widget(form)}}
{{form_end(form)}}
 
</div>




{% endblock %}

templates/Films/film.html.twig
{% extends "base.html.twig" %}

{% block title %}Property{% endblock %}



{% block body %}


<div class="container">
    




<div class="row">
    <div class="col-md-8">
        <h2>Le film séléctionné</h2>
        <img src="{{asset('uploads/'~film.affiche)}}" style="width: 200px">
        <table class="table table-striped">
<tr>
    <td>Titre de film</td>
    <td>{{film.titre}}</td>
   
</tr>
<tr>
    <td>Résumé du film</td>
    <td>{{film.resume}}</td>
   
</tr>
<tr>
    <td>Année de sortie</td>
    <td>{{film.anneeDeSortie|date("d/m/Y")}}</td>
   
</tr>
<tr>
    <td>Genre du film</td>
    <td><a href="{{path("listg",{id:film.id})}}">{{film.genre.nom}}</td>
   
</tr>
<tr>
    <td>Acteurs du film</td>
    {% for acteur in film.acteurs %}
   
    <td><a href="{{path("acteur",{id:acteur.id})}}">{{acteur.nom}}</td>
    {%endfor%}
  

</tr>


</table>
    </div>
</div>


{% endblock %}

templates/Films/search.html.twig
{% extends "base.html.twig" %}

{% block title %}Property{% endblock %}



{% block body %}


 

<div class="container">
    <div class="row flex">
            
        {% for recherche in recherches %}
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <img src="{{asset('uploads/'~recherche.affiche)}}" style="width: 100px">
                    <h5 class="card-title">
                        
                        <a href="{{path('film',{id:recherche.id})}}">{{ recherche.titre}}</a>
                    </h5>
                    <p class="card-text">{{recherche.resume}}</p>
      
                </div>
            </div>
                </div>
        {% endfor %}
            </div>
        </div>


{% endblock %}